logging:
  file: logs/oath2-sso.log
  level:
    root: info

server:
  port: 9992

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  oauth2:
    resource:
      token-info-uri: ${auth-server:http://localhost:9991/uaa}/oauth/check_token
    client:
      client-id: demo
      client-secret: demo