logging:
  file: logs/oath2-sso.log
  level:
    root: info
    com.bdfint. sso: debug
    org.springframework.security: DEBUG

server:
  port: 9993

spring:
  application:
    name: auth-server
  aop:
    proxy-target-class: true
  jackson:
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

auth-server: http://localhost:9999/uaa

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: demo
      client-secret: demo
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: read, write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
